name: Compile

on:
   push:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: ./KBotExt.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  RUN_NUMBER: ${{github.run_number}}

permissions:
  contents: read

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[build]')"
    name: Build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.1.3
      with:
        msbuild-architecture: x64

    - name: Build KBotExt solution
      working-directory: ./
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload KBotExt latest artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: KBotExt-${{env.RUN_NUMBER}}
        path: ./x64/Release/KBotExt.exe
        if-no-files-found: error
